create table t_auth_refresh_session (
    session_id varchar(64) not null comment 'Access JWT sid 与 refresh family 标识',
    user_id bigint not null comment '全局用户ID',
    client_instance_id varchar(128) not null comment '浏览器实例非敏感标识',
    context_type varchar(32) not null comment 'PLATFORM/PLATFORM_TENANT/TENANT',
    tenant_id bigint default null,
    tenant_code varchar(64) default null,
    tenant_role varchar(24) default null,
    tenant_context_version bigint default null,
    member_context_version bigint default null,
    security_version bigint not null default 0 comment '安全事件代际，阻止旧 Access/operation token 复活',
    authorities_json varchar(1000) not null default '[]',
    status varchar(16) not null default 'ACTIVE',
    absolute_expires_at datetime not null,
    current_token_id varchar(64) default null,
    user_agent_hash char(64) not null,
    initial_ip_network_hash char(64) not null,
    last_ip_network_hash char(64) not null,
    ip_change_count int not null default 0,
    user_agent_change_count int not null default 0,
    step_up_required tinyint not null default 0,
    revoked_at datetime default null,
    revoke_reason varchar(64) default null,
    version int not null default 0,
    create_time datetime not null default current_timestamp,
    update_time datetime not null default current_timestamp on update current_timestamp,
    primary key (session_id),
    key idx_auth_refresh_session_user (user_id, status),
    key idx_auth_refresh_session_expiry (status, absolute_expires_at),
    check (context_type in ('PLATFORM', 'PLATFORM_TENANT', 'TENANT')),
    check (status in ('ACTIVE', 'REVOKED', 'EXPIRED')),
    check (step_up_required in (0, 1))
) default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='认证 Refresh Session';

create table t_auth_refresh_token (
    token_id varchar(64) not null,
    session_id varchar(64) not null,
    token_hash char(64) not null comment '高熵 refresh token 的 SHA-256 哈希',
    status varchar(16) not null default 'ACTIVE',
    issued_at datetime not null,
    consumed_at datetime default null,
    expires_at datetime not null,
    replaced_by_token_id varchar(64) default null,
    user_agent_hash char(64) not null,
    ip_network_hash char(64) not null,
    create_time datetime not null default current_timestamp,
    update_time datetime not null default current_timestamp on update current_timestamp,
    primary key (token_id),
    unique key uk_auth_refresh_token_hash (token_hash),
    key idx_auth_refresh_token_session (session_id, status),
    check (status in ('ACTIVE', 'ROTATED', 'REPLAYED', 'REVOKED', 'EXPIRED'))
) default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Refresh Token 旋转历史';

create table t_auth_refresh_risk_event (
    event_id bigint not null auto_increment,
    session_id varchar(64) not null,
    event_type varchar(32) not null,
    previous_signal_hash char(64) default null,
    current_signal_hash char(64) default null,
    create_time datetime not null default current_timestamp,
    primary key (event_id),
    key idx_auth_refresh_risk_session (session_id, create_time),
    check (event_type in ('IP_NETWORK_CHANGED', 'USER_AGENT_CHANGED', 'CLIENT_INSTANCE_CHANGED', 'STEP_UP_REQUIRED', 'STEP_UP_COMPLETED'))
) default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Refresh Session 弱风险信号变化历史';
